---
myname: vpn.ziberhub.eus
vpngw: "vpn.ziberhub.eus"
registry_user: registry
registry_home: "/home/registry"
registry_storage: "/home/registry/storage"
registry_bind_ip: "0.0.0.0"
registry_bind_port: "5000"
egress_if: "vio0"
targets_if: "vio3"
interconnect_interface: vio2
vpn_ext_ip: "172.26.0.254"
interconnect_interface_ip: 172.24.0.254
targets_if_ipv4: "10.4.0.254"
GITHUB_OAUTH_TOKEN: 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
targets_subnet: "10.4.0.0"
targets_netmask: "255.255.0.0"
echoCTF_VPN_mgmt_passwd: "openvpn"
offense_network: "10.10.0.0/24"
db_host: "172.24.0.253"
db_name: "echoCTF"
db_user: "vpnuser"
db_pass: "vpnuserpass"
GITHUB_REPO: git@github.com:proditis/ziberhub.eus.git